/**
 * The datasets behind the app.
 *
 * `wired` distinguishes sources the code actually calls from ones documented as options
 * in docs/ROSTER.md but not yet implemented. Listing an unused dataset as though it were
 * powering the app would be the sort of credit that is really a boast, so the distinction
 * is shown in the UI rather than smoothed over.
 */

export const SOURCES = [
  {
    id: 'wikidata',
    name: 'Wikidata',
    url: 'https://www.wikidata.org',
    license: 'CC0 1.0 — public domain dedication',
    wired: true,
    what: 'Birth and death years, English labels and descriptions, portrait file names, and the sitelink counts used as the fame score.',
    how: 'Queried through the Action API (wbgetentities), batched fifty entities at a time, by tools/roster-wikidata.mjs and tools/draft-card.mjs.',
    note: 'Not queried through SPARQL: the public WDQS endpoint times out on any scan over wikibase:sitelinks. The Action API returns identical counts.',
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia (English)',
    url: 'https://en.wikipedia.org',
    license: 'CC BY-SA 4.0',
    wired: true,
    what: 'Biographical article text — the raw material a character card is drafted from, and the category trees used to find roster candidates.',
    how: 'REST summary endpoint and the Action API (prop=extracts, list=categorymembers), in tools/draft-card.mjs and tools/roster-wikidata.mjs.',
  },
  {
    id: 'wikiquote',
    name: 'Wikiquote',
    url: 'https://en.wikiquote.org',
    license: 'CC BY-SA 4.0',
    wired: true,
    what: 'Sourced quotations. These become the sample_lines on a card — the few-shot voice anchors that stop every figure sounding like the same assistant.',
    how: 'Action API extracts, in tools/draft-card.mjs. The drafting prompt may only use quotations that appear verbatim in the fetched material, and is instructed to return an empty list rather than reconstruct one from memory.',
    note: 'Every quotation on a card carries a source and a verified flag. Figures with no reliable verbatim record — Cleopatra, Genghis Khan — ship with no quotations at all and a voice note instead.',
  },
  {
    id: 'commons',
    name: 'Wikimedia Commons',
    url: 'https://commons.wikimedia.org',
    license: 'Per file — every portrait shipped here is public domain',
    wired: true,
    what: 'The portraits shown beside each line of dialogue and in the roster search, resampled in the browser and colour-quantised so they sit alongside the pixel art.',
    how: 'Fetched via Special:FilePath and pixelated client-side on a canvas.',
    note: 'The standing sprites are drawn rather than photographic. A fourteen-pixel crop of an oil painting is indistinguishable from noise, so each figure is built from documented features — hair, beard, headwear, garment — which is what actually makes someone recognisable at that size.',
  },
  {
    id: 'pantheon',
    name: 'Pantheon',
    url: 'https://pantheon.world',
    license: 'See the download page at pantheon.world',
    wired: true,
    what: 'Fame ranking. Pantheon 1.0 is about 11,000 manually verified biographies with birth dates, an occupation taxonomy, and two fame measures — L (language-edition count) and HPI (Historical Popularity Index). The expanded set reaches roughly 89,000.',
    how: 'tools/roster-pantheon.mjs imports a person-level CSV. The download is deliberately manual: Pantheon’s endpoints move, and a silently-wrong file is worse than a step you do yourself.',
    note: 'HPI is the better fame signal because it weighs page views and time depth rather than counting how many wikis created a stub.',
  },
  {
    id: 'crossverified',
    name: 'Cross-verified database of notable people, 3500BC–2018AD',
    url: 'https://doi.org/10.1038/s41597-022-01369-4',
    license: 'CC BY 4.0 — Sciences Po Dataverse',
    wired: false,
    what: '2.29 million individuals, built by deduplicating and cross-verifying multiple Wikipedia editions against Wikidata. About a third are absent from English Wikipedia.',
    how: 'Documented in docs/ROSTER.md as the ceiling for roster scale. No importer is wired up yet.',
    note: 'Laouenan et al., Scientific Data 9, 290 (2022). Error rates climb toward the bottom of the notability distribution — which is where the fame floor already advises against going.',
  },
  {
    id: 'avalon',
    name: 'The Avalon Project, Yale Law School',
    url: 'https://avalon.law.yale.edu',
    license: 'Free access for scholarly use',
    wired: false,
    what: 'Primary diplomatic and legal documents — the actual Tehran declarations behind the ground-truth beats in that scenario.',
    how: 'A human research source used while writing scenario cards. Not called by any code.',
  },
];

export const MODELS = {
  what: 'Dialogue is generated by Google Gemini models — a larger one for the characters, a cheaper one for the director, summarizer and moderation checks.',
  note: 'The app also ships a mock provider that runs the whole stack with no key and no network, producing obvious placeholder text. If you see a MOCK badge, that is what you are reading.',
};

export const ART = {
  what: 'Every sprite and backdrop is drawn in code — no art assets, no image files. Each figure is composed from a garment silhouette, hair, beard and headwear chosen from the documented record, on a 32×56 pixel grid.',
  note: 'They are stylised representations, not likenesses. Where a real portrait exists it appears beside the dialogue instead.',
};

export const FONTS = [
  { name: 'Press Start 2P', by: 'CodeMan38', license: 'SIL Open Font License 1.1' },
  { name: 'Pixelify Sans', by: 'Stefie Justprince', license: 'SIL Open Font License 1.1' },
  { name: 'Silkscreen', by: 'Jason Kottke', license: 'SIL Open Font License 1.1' },
];
